Repository jitacm/30_days_cpp-2D-engine-, pull requests merged in 2025-08, with the labels that each got.

#2 Physics Engine Core Implementation Done #1
  2D_Engine/Game.cpp
  2D_Engine/include/Config.h
  2D_Engine/include/RigidBody.h
  2D_Engine/include/Utils.h
  2D_Engine/include/Vector2.h
  2D_Engine/include/World.h
  2D_Engine/src/RigidBody.cpp
  2D_Engine/src/Utils.cpp
  2D_Engine/src/World.cpp
  2D_Engine/src/main.cpp
Labels: 30daysdevchallenge, jitacm, feature, level-4

#4 Comprehensive README Enhancement: Add detailed documentation, installation guide & technical explanations
  README.md
Labels: documentation, 30daysdevchallenge, jitacm, level-2

#9 Collision Detection & Resolution System Added #8
  2D_Engine/include/CircleShape.h
  2D_Engine/include/Collision.h
  2D_Engine/include/RectangleShape.h
  2D_Engine/include/RigidBody.h
  2D_Engine/include/Shape.h
  2D_Engine/include/Vector2.h
  2D_Engine/include/World.h
  2D_Engine/src/Collision.cpp
  2D_Engine/src/RigidBody.cpp
  2D_Engine/src/World.cpp
  2D_Engine/src/main.cpp
Labels: 30daysdevchallenge, jitacm, feature, level-3

#21 Implemented Scene Management, Advanced Debugging Tools, and Full Collision Support #20
  2D_Engine/include/CircleShape.h
  2D_Engine/include/Collision.h
  2D_Engine/include/Config.h
  2D_Engine/include/RectangleShape.h
  2D_Engine/include/RigidBody.h
  2D_Engine/include/Scene.h
  2D_Engine/include/SceneManager.h
  2D_Engine/include/Shape.h
  2D_Engine/include/Vector2.h
  2D_Engine/include/World.h
  2D_Engine/src/Collision.cpp
  2D_Engine/src/RigidBody.cpp
  2D_Engine/src/Scene.cpp
  2D_Engine/src/SceneManager.cpp
  2D_Engine/src/World.cpp
  2D_Engine/src/main.cpp
Labels: 30daysdevchallenge, jitacm, feature, level-2
